version: '3.6'

services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
